### ISSUE TITLE
Breaking change when updating ^0.0.5 -> ^0.0.9

### ISSUE THREAD

**Issue by JoostvdB94** [dweber019/backstage-plugins#19]
Today, when updating the "@dweber019/backstage-plugin-api-docs-module-wsdl-backend" package from 0.0.5 to 0.0.9, the build was breaking with the following error.

```
yarn tsc:
   Type '{ logger: Logger; }' is missing the following properties from type 'RouterOptions': discovery, tokenManager
 
   return await createRouter({ logger: env.logger });
                              ~~~~~~~~~~~~~~~~~~~~~~
```

I suspect that this was caused by a breaking change in the upgrade. However, the version increase suggests otherwise. Should this have been an major version upgrade?

**Comment by dweber019** [comment]
@JoostvdB94 thanks for reporting. Was not intentional and should be mentioned in the change logs for sure.

**Comment by JoostvdB94** [comment]
@dweber019 Thanks for mentioning the breaking change in the changelog this time. 
Would it also be possible to adhere to the rules of [semantic versioning](https://semver.org/)? Renovate sees these types of upgrades as minor (which should not have breaking changes). Different version upgrades (patch,minor or major) could have different upgrade strategies (such as bundling all minor and/or patch upgrades, or having higher frequency patch and minor upgrades than major upgrades).

Besides tooling, having semver is more transparent to users.
