### ISSUE TITLE
[end-of-life plugin] Add missing peer dependencies for vis-data and xss

### ISSUE THREAD

**Issue by manusant** [dweber019/backstage-plugins#29]
The **vis-timeline** dependency sets some peer dependencies that needs to be set in order to have the dependency graph set properly.

Currently your plugin is not providing them and this makes use of the plugin really hard and confusing. 

I kindly ask you to provide the required dependencies as part of your plugin to make sure versions are aligned.
Currently failing for **vis-data**, **vis-util** and **xss** libraries but not sure because the vis-timeline sets a bunch of peer dependencies.

To get the typescript issues, please run: 
````shell

tsc --skipLibCheck false --incremental false
````

**Comment by dweber019** [comment]
Having a look into this in the next few days.
Would be open for PR's too 🙏

**Comment by dweber019** [comment]
Fix released
