### ISSUE TITLE
license information

### ISSUE THREAD

**Issue by shivabasu** [dweber019/backstage-plugins#36]
please add license information 
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by dweber019** [comment]
See https://github.com/dweber019/backstage-plugins?tab=MIT-1-ov-file#readme

Additionally, there is a special license for saxonjs, see https://github.com/dweber019/backstage-plugins/tree/main/plugins/api-docs-module-wsdl-backend.

Is there anything missing for you?
