### ISSUE TITLE
Payload too large for some large wsdl-files

### ISSUE THREAD

**Issue by oliverdirks** [dweber019/backstage-plugins#4]
Hi @dweber019,

first of all, i would thank your for this nice plugin. We tested in in our backstage instance and it fits good. Currently we are facing problems with the payload of some wsdl-files which are too large.

Plugin: `api-docs-module-wsdl-backend`

The answer for my request shows the following error message.
```json
{
    "error": {
        "name": "PayloadTooLargeError",
        "message": "request entity too large",
        "expected": 132270,
        "length": 132270,
        "limit": 102400,
        "type": "entity.too.large"
    },
    "request": {
        "method": "POST",
        "url": "/api/api-docs-module-wsdl/v1/convert?entityRef=api:gothaer-private/partnerleseservice-partner-soap"
    },
    "response": {
        "statusCode": 413
    }
}
```

**Comment by dweber019** [comment]
Hi @oliverdirks 
Thanks.
Could you give an example of a wsdl.

**Comment by dweber019** [comment]
Cloud replicate the issue. Created PR.
