### ISSUE TITLE
Dark-Mode support for api-docs-module-wsdl

### ISSUE THREAD

**Issue by oliverdirks** [dweber019/backstage-plugins#5]
Hey :) 

we are testing the api-docs-module-wsdl at the moment. We support the dark and light mode in our backstage instance. It seems like the plugin dont. Its very hard to read the wsdl-spec when the dark mode is enabled.

It would be great if this plugin would support the dark mode too

![grafik](https://github.com/dweber019/backstage-plugins/assets/131759094/699f298d-61d6-4769-8655-fd4d0bd4d3b8)

**Comment by dweber019** [comment]
@oliverdirks created a PR with sample images. Would this be as you imagined?

**Comment by oliverdirks** [comment]
Hi @dweber019,

this look great! 

Thank you for your fast response
