### ISSUE TITLE
Tips - add option to only show tips to entity owners

### ISSUE THREAD

**Issue by darylgraham** [dweber019/backstage-plugins#57]
We use permissions to disable the unregister entity button when the user is not an owner of an entity. I feel like this is fairly standard since it is an example in the permissions docs.

This creates a culture of entity ownership, so it feels odd to have tips popping up telling you to update metadata for entities you do not own. If we had a configuration option or component parameter allowing us to set tips to only show when the user is an owner (or has `catalog.update` permissions), it would allow the tips plugin to fit into our workflow a lot more seamlessly.

A much bigger modification (I think) could be to enable a potential permissions check for each tip, so that every tip could be targeted to users with the correct permission. That would mean entity modification tips would not show for non-owners, but other tips could still be shown when applicable.

**Comment by dweber019** [comment]
Hey @darylgraham 

Nice ideas. I would go with the ownership instead of the permission.
I would do this with the activate option https://github.com/dweber019/backstage-plugins/blob/main/plugins/tips/src/config.ts#L18 but we would need to pass the indentity service to reason about the ownerships the current user has.

**Comment by dweber019** [comment]
@darylgraham created pr https://github.com/dweber019/backstage-plugins/pull/59
Could you have a review?

**Comment by darylgraham** [comment]
@dweber019 I've had a play with that branch and it does everything it should. My user sees all tips when listed as an owner both by user directly and group membership, and they are no longer visible for entities that I do not own.

I don't have enough experience with TS/Backstage to comment on how good the code is.

**Comment by dweber019** [comment]
Thanks for testing. Then let's merge this as we only changed some minor stuff.
