### ISSUE TITLE
Missing Entities - ability to integrate with Devtools

### ISSUE THREAD

**Issue by darylgraham** [dweber019/backstage-plugins#58]
The MissingEntitiesPage seems perfect to go into DevTools beside the UnregisteredEntities page. Unfortunately the component includes a page header, so I get two headers when embedding it within DevTools.

Options would be to expose the page content as a separate component, or add a parameter to toggle the header display. I’m not sure which is the best pattern.

**Comment by dweber019** [comment]
Created a pr for this https://github.com/dweber019/backstage-plugins/pull/60
