### ISSUE TITLE
EntityPage configuration suggestions in documentation

### ISSUE THREAD

**Issue by jnmaih** [dweber019/backstage-plugins#68]
Hi @dweber019, thanks a lot for that very useful plugin, it is very appreciated by our users!

We had to do the following changes in EntityPage.tsx compared to the documented steps in Readme.MD:

- We had to add isEndOfLifeAvailable to line

   import { EntityEndOfLifeCard, isEndOfLifeAvailable, } from '@dweber019/backstage-plugin-endoflife';
   in first option for packages/app/src/components/catalog/EntityPage.tsx
   
   
- In this block:

    <EntitySwitch>
      <EntitySwitch.Case if={hasLabels}>
        <Grid item md={4} xs={12}>
          <EntityLabelsCard />
        </Grid>
      </EntitySwitch.Case>
    </EntitySwitch>
    <EntitySwitch>
      <EntitySwitch.Case if={isEndOfLifeAvailable}>
        <Grid item md={6}>
          <EntityEndOfLifeCard />
        </Grid>
      </EntitySwitch.Case>
    </EntitySwitch>
    
we had to do this instead:

    <EntitySwitch>
      <EntitySwitch.Case if={isEndOfLifeAvailable}>
        <Grid item md={6}>
          <EntityEndOfLifeCard />
        </Grid>
      </EntitySwitch.Case>
    </EntitySwitch>
    
mean, remove the first EntitySwitch block.

Does this make sense to you?

Best regards
  Juergen

**Comment by dweber019** [comment]
Hi @jnmaih 

Thanks a lot, appreciate that and happy that it's useful for you and your users.

You are totally right, the `isEndOfLifeAvailable` should be imported.
If you mean for the `mean, remove the first EntitySwitch block.` to remove the block containing `<EntityLabelsCard />`, you are right too.

I will correct this right away. Thanks for the feedback
